package org.apache.hadoop.hbase.regionserver;

import edu.illinois.core.instance.UpgradableInstance;
import java.lang.reflect.Constructor;

/**
 * Instance helper class for creating HRegionServer instances
 * using version-specific classloaders.
 * Generated by UpgradableClusterGenerator.
 */
public class HRegionServerInstance extends UpgradableInstance {

    public HRegionServerInstance(UpgradableInstance delegate) {
        super(delegate.getNodeName(), delegate.getVersion(),
                delegate.getLoader(), delegate.getPlan(),
                delegate.isMarkedForUpgrade());
        //CompatibilityFactory.getInstance(MetricsAssertHelper.class).init();
        // Use reflection to call the above init() method
        try {
          // set TCCL
          enter();
          Class<?> compatFactoryClass = getLoader().loadClass("org.apache.hadoop.hbase.CompatibilityFactory");
          Class<?> metricsHelperClass = getLoader().loadClass("org.apache.hadoop.hbase.test.MetricsAssertHelper");
          java.lang.reflect.Method getInstance = compatFactoryClass.getMethod("getInstance", Class.class);
          Object metricsHelper = getInstance.invoke(null, metricsHelperClass);
          java.lang.reflect.Method initMethod = metricsHelperClass.getMethod("init");
          initMethod.invoke(metricsHelper);
          exit();
        } catch (Exception e) {
            throw new RuntimeException("Failed to initialize MetricsAssertHelper: " + e.getMessage(), e);
        }
    }

    /**
     * Creates a HRegionServer instance for use in InJVM cluster.
     * This method uses reflection to instantiate the node with the version-specific classloader.
     */
    public HRegionServerJVMInterface createHRegionServerForInJVMCluster(Object... args) {
        enter();
        try {
            Class<?> nodeClass = getLoader().loadClass("org.apache.hadoop.hbase.regionserver.HRegionServer");
            Constructor<?> constructor = findMatchingConstructor(nodeClass, args);
            Object instance = constructor.newInstance(args);
            return (HRegionServerJVMInterface) instance;
        } catch (Exception e) {
            throw new RuntimeException("Failed to create HRegionServer instance: " + e.getMessage(), e);
        } finally {
            exit();
        }
    }

    private Constructor<?> findMatchingConstructor(Class<?> clazz, Object... args) {
        Constructor<?>[] constructors = clazz.getConstructors();
        for (Constructor<?> constructor : constructors) {
            if (constructor.getParameterCount() == args.length) {
                return constructor;
            }
        }
        throw new RuntimeException("No matching constructor found for " + clazz.getName() +
                " with " + args.length + " arguments");
    }
}
